parking_project/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from parking_reservation import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.IndexView.as_view()),
    url(r'^parking_reservation/', include('parking_reservation.urls', namespace='parking_reservation'))

]

parking_reservation/urls.py
from django.conf.urls import url
from parking_reservation import views

app_name = 'parking_reservation'

urlpatterns = [
    url(r'^$', views.ParkingListView.as_view(), name='list'),
                                              # This name List is for the URL template tag
    url(r'^(?P<pk>\d+)/$', views.ParkingDetailview.as_view(), name='detail'),
    #   <pk> - primary key
    #   [-\w+] alphanumeric (alphabetic and numeric) characters
    #   primary key followed by one or more alphanumeric number
    url(r'^create/', views.ParkingCreateView.as_view(), name='create'),
    url(r'^update/(?P<pk>\d+)/$', views.ParkingUpdateView.as_view(), name='update'),
    url(r'^delete/(?P<pk>\d+)/$', views.ParkingDeleteView.as_view(), name='delete'),
    url(r'^createslot/', views.ParkingslotCreateView.as_view(), name='createslot'),
    url(r'^updateslot/(?P<pk>\d+)/$', views.ParkingslotUpdateView.as_view(), name='updateslot'),

]

parking_reservation/models.py
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.
class Parking(models.Model):
    slot_name = models.CharField(max_length=256)
    lane = models.CharField(max_length=256, default='WestLane')
    locality = models.CharField(max_length=256,default='Magarpatta')
    def __str__(self):
        return self.locality+'->'+self.lane+'->'+self.slot_name

    def get_absolute_url(self):
        return reverse('parking_reservation:detail', kwargs={'pk':self.pk}) # pk stands for Primary Key

class SlotDetail(models.Model):
        slot = models.ForeignKey(Parking,related_name='slotDetails')
        start_date = models.DateField(auto_now=False, auto_now_add=False)
        end_date = models.DateField(auto_now=False, auto_now_add=False)
        reserved = models.BooleanField(default=False)

        def __str__(self):
            return 'Slot->'+self.slot.slot_name

        def get_absolute_url(self):
            return reverse('parking_reservation:detail', kwargs={'pk':self.slot.pk}) # pk stands for Primary Key

parking_reservation/forms.py
import datetime
from django import forms
from parking_reservation.models import SlotDetail
from django.forms import ModelForm, DateInput, TextInput, ValidationError

class SlotDetailForm(ModelForm):
    class Meta():
        model = SlotDetail
        fields = '__all__'

        widgets = {
            # The class here is a CSS class.
            'start_date' : DateInput(attrs={'type': 'date'}),
            'end_date'  : DateInput(attrs={'type': 'date'}),
        }

# Additional custom validator for start_date / finish_date fields
    def clean(self):
        data = self.cleaned_data
        start_date = data['start_date']
        end_date = data['end_date']

        if start_date > end_date:
            raise ValidationError('Wrong start and end dates.')

        if start_date < datetime.date.today():
            raise ValidationError('Start date in the past.')

        return data

parking_reservation/views.py
from django.shortcuts import render
from django.views.generic import (View, TemplateView,
                                    ListView, DetailView,
                                    CreateView, UpdateView,
                                    DeleteView)

from parking_reservation import models
from django.core.urlresolvers import reverse_lazy
from parking_reservation.forms import SlotDetailForm


# Create your views here.
class ParkingListView(ListView):
    # The ListView is creating a school_list for us and returning
    # It takes the model you called (School), lower cases everythhing
    #and returns a list with school_list
    context_object_name = 'parkings' # This will make the class no longer return parking_list but
                                    #a object calld parkings
    model = models.Parking

class ParkingDetailview(DetailView):
    #   Differently of the ListView, the DetailView just returns the name in
    #lower case. Here, just school
    context_object_name = 'parking_detail'
    model = models.Parking
    template_name = 'parking_reservation/parking_detail.html'

class ParkingUpdateView(UpdateView):
    fields = ('locality','lane','slot_name')
    model = models.Parking

class ParkingslotUpdateView(UpdateView):
    fields = ('reserved',)
    model = models.SlotDetail

class ParkingCreateView(CreateView):
    fields = ('locality','lane','slot_name')
    model = models.Parking

class ParkingslotCreateView(CreateView):
    #fields = ('slot','start_date','end_date','reserved')
    model = models.SlotDetail
    form_class = SlotDetailForm
    #def form_valid(self, form):
    #    form.instance.slot = self.request.slot_name
    #    return super(ParkingslotCreateView, self).form_valid(form)


class ParkingDeleteView(DeleteView):
    model = models.Parking
    success_url = reverse_lazy("parking_reservation:list")

class IndexView(TemplateView):

    # This probably happens because, I think, TemplateView is an abstract class.
    template_name = 'index.html' #this is the name of our tamplate. Remmember: this variable HAS to be named template_name !!!!

parking_reservation/templates/parking_reservation/parking_confirm_delete.html
{% extends "parking_reservation/parking_reservation_base.html" %}
{% block body_block %}
  <h1>Delete {{parking.slot_name}}?</h1>

  <form method="post">
    {% csrf_token %}
    <input type="submit" class="btn btn-danger" value="Delete">
    <!-- NOTE: here we must pass the pk=parking.pk because in the parking_reservation:detail view, in urls.py
    the regex expects a primary key value (pk) -->
    <a href="{% url 'parking_reservation:detail' pk=parking.pk %}">Cancel</a>
  </form>
{% endblock %}

parking_reservation/templates/parking_reservation/parking_detail.html
{% extends 'parking_reservation/parking_reservation_base.html' %}

{% block body_block %}
<div class="jumbotron">
  <h2>Parking Details are:</h2>
  <p>Locality: {{parking_detail.locality}}
     Lane: {{parking_detail.lane}}
     Slot: {{parking_detail.slot_name}}
</p>

  <h3>SlotDetail</h3>
  <!-- NOTE: the parking_list is the context_object_name we provided in parking_reservation/views.py
    The tricky part here is the parking_detail.slotDetails . This is the related_name on SlotDetails.
    It is like going to the SQL and query for all students in that particular parking, since parking
  is a ForeignKey for the SlotDetails.  -->
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Start Date</th>
        <th>End Date</th>
        <th>Reserved</th>
        <th>Reserve/Cancel</th>
      </tr>
    </thead>
    <tbody>
      {% for slotdetails in parking_detail.slotDetails.all %}
      <tr>
        <td>{{slotdetails.start_date}}</td>
        <td>{{slotdetails.end_date}}</td>

        {% if slotdetails.reserved %}
        <td>Yes</td>
        <td><a class="btn btn-warning" href="{% url 'parking_reservation:updateslot' pk=slotdetails.pk%}">Cancel</a></td>
        {% else %}
        <td>No</td>
        <td><a class="btn btn-success" href="{% url 'parking_reservation:updateslot' pk=slotdetails.pk%}">Reserve</a></td>
        {% endif %}

      </tr>
      {% endfor %}
    </tbody>
  </table>
  <a class="btn btn-warning" href="{% url 'parking_reservation:createslot'%}">Add</a>

</div>

<div class="container">
  <p><a class="btn btn-warning" href="{% url 'parking_reservation:update' pk=parking_detail.pk%}">Update</a></p>
  <a class="btn btn-danger" href="{% url 'parking_reservation:delete' pk=parking_detail.pk%}">Delete</a>

</div>

{% endblock %}

parking_reservation/templates/parking_reservation/parking_form.html
{% extends "parking_reservation/parking_reservation_base.html" %}
{% block body_block %}
  <h1>
    {% if not form.instance.pk %}
      Create Parking
    {% else %}
      Update Parking
    {% endif %}
  </h1>

  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" name="btn btn-primary" value="Submit">
  </form>
{% endblock %}

parking_reservation/templates/parking_reservation/parking_list.html
{% extends "parking_reservation/parking_reservation_base.html" %}

{% block body_block %}
<div class="jumbotron">
  <h1> List of Parkings!</h1>
  <table class="table table-striped">
  <thead>
    <tr>
      <th>Locality</th>
      <th>Lane</th>
      <th>Slot Name</th>
    </tr>
  </thead>
  <tbody>
    {% for parking in parkings %}
    <tr>
      <td>{{parking.locality}}</td>
      <td>{{parking.lane}}</td>
      <td><a href="{{parking.id}}">{{parking.slot_name}}</a></td>
    </tr>
    {% endfor %}
  </tbody>
</table>
</div>
<div class="container">
  <p><a class="btn btn-warning" href="{% url 'parking_reservation:create' %}">Create</a></p>

</div>
{% endblock %}

parking_reservation/templates/parking_reservation/parking_reservation_base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>PARKING APP!</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <ul class="nav navbar-nav">
        <li><a class="navbar-brand" href="{% url 'parking_reservation:list' %}">Parking</a></li>
        <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
      </ul>

    </nav>
    <div class="container">
      {% block body_block %}

      {% endblock %}
    </div>

  </body>
</html>

parking_reservation/templates/parking_reservation/slotdetail_form.html
{% extends "parking_reservation/parking_reservation_base.html" %}
{% block body_block %}
  <h1>
    {% if not form.instance.pk %}
      Create Parkingslot
    {% else %}
      Update Parkingslot
    {% endif %}
  </h1>

  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" name="btn btn-primary" value="Submit">
  </form>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>PARKING APP!</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <ul class="nav navbar-nav">
        <!-- Remmember: the URL template is referring to parking_reservation urls.py, and calling the URL named 'list' -->
        <li><a class="navbar-brand" href="{% url 'parking_reservation:list' %}">Parking</a></li>
        <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>

      </ul>

    </nav>
    <div class="container">
      {% block body_block %}

      {% endblock %}
    </div>

  </body>
</html>

templates/index.html
{% extends "base.html" %}
{% block body_block %}
  <div class="jumbotron">
    <h1>Parking Reservation App!</h1>
  </div>
{% endblock %}